language: python
sudo: required
services:
  - docker

install:
  - pip install flake8

script:
  - pip install --no-cache-dir -e .
  - make lint

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
