language: python
sudo: required
services:
  - docker

before_install:
  - pip install flake8

install:
  - make lint
  - make build

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
